// This code is auto generated by Excel VBA. Do NOT edit it manually !
// Copyright (C) 2016 Nanjing Xiaoxi Network Technology Co., Ltd. (http://www.xiaoxigame.com/)

using XPlugin.Localization;

public static partial class LString
{
	/// <summary>
	/// 加载Client_Script_Text
	/// </summary>
	public static void Load_Client_Script_Text()
	{
		LocalizedDict.Load("Client_Script_Text");
	}
	
	/// <summary>
	/// 正在加载客户端数据...
	/// </summary>
	public const string GAMECLIENT_CLIENT_INITDATA = "GAMECLIENT_CLIENT_INITDATA";
	
	/// <summary>
	/// 网络对战
	/// </summary>
	public const string GAMECLIENT_DATADEF = "GAMECLIENT_DATADEF";
	
	/// <summary>
	/// 淘汰赛
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODENAME = "GAMECLIENT_DATADEF_GAMEMODENAME";
	
	/// <summary>
	/// 计时赛
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODENAME_1 = "GAMECLIENT_DATADEF_GAMEMODENAME_1";
	
	/// <summary>
	/// 竞速道具赛
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODENAME_2 = "GAMECLIENT_DATADEF_GAMEMODENAME_2";
	
	/// <summary>
	/// 淘汰道具赛
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODENAME_3 = "GAMECLIENT_DATADEF_GAMEMODENAME_3";
	
	/// <summary>
	/// 竞速赛
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODENAME_4 = "GAMECLIENT_DATADEF_GAMEMODENAME_4";
	
	/// <summary>
	/// 击杀赛
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODENAME_5 = "GAMECLIENT_DATADEF_GAMEMODENAME_5";
	
	/// <summary>
	/// 错误模式
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODENAME_6 = "GAMECLIENT_DATADEF_GAMEMODENAME_6";
	
	/// <summary>
	/// 倒计时结束前不要落到最后一名
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODEDESC = "GAMECLIENT_DATADEF_GAMEMODEDESC";
	
	/// <summary>
	/// 在规定时间内完成比赛
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODEDESC_1 = "GAMECLIENT_DATADEF_GAMEMODEDESC_1";
	
	/// <summary>
	/// 领先其他对手完成比赛，可以使用道具
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODEDESC_2 = "GAMECLIENT_DATADEF_GAMEMODEDESC_2";
	
	/// <summary>
	/// 倒计时结束前不要落到最后一名，可以使用道具
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODEDESC_3 = "GAMECLIENT_DATADEF_GAMEMODEDESC_3";
	
	/// <summary>
	/// 领先其他对手完成比赛
	/// </summary>
	public const string GAMECLIENT_DATADEF_GAMEMODEDESC_4 = "GAMECLIENT_DATADEF_GAMEMODEDESC_4";
	
	/// <summary>
	/// 挑战每天刷新！<para/>挑战成功可获取奖品！<para/>每天挑战次数有限！
	/// </summary>
	public const string GAMECLIENT_MODCHALLENGE = "GAMECLIENT_MODCHALLENGE";
	
	/// <summary>
	/// 赛事持续时间有限！<para/>赛事结束可获取奖品！<para/>已结束的赛事保留3天！<para/>新赛事不断更新中！
	/// </summary>
	public const string GAMECLIENT_MODCHAMPIONSHIP = "GAMECLIENT_MODCHAMPIONSHIP";
	
	/// <summary>
	/// 网络错误
	/// </summary>
	public const string GAMECLIENT_MODCHAMPIONSHIP_UPLOADRESULT = "GAMECLIENT_MODCHAMPIONSHIP_UPLOADRESULT";
	
	/// <summary>
	/// 成绩上传失败，是否重新上传？
	/// </summary>
	public const string GAMECLIENT_MODCHAMPIONSHIP_UPLOADRESULT_1 = "GAMECLIENT_MODCHAMPIONSHIP_UPLOADRESULT_1";
	
	/// <summary>
	/// 确定
	/// </summary>
	public const string GAMECLIENT_MODCHAMPIONSHIP_UPLOADRESULT_2 = "GAMECLIENT_MODCHAMPIONSHIP_UPLOADRESULT_2";
	
	/// <summary>
	/// 取消
	/// </summary>
	public const string GAMECLIENT_MODCHAMPIONSHIP_UPLOADRESULT_3 = "GAMECLIENT_MODCHAMPIONSHIP_UPLOADRESULT_3";
	
	/// <summary>
	/// 加载中...
	/// </summary>
	public const string GAMECLIENT_MODGAME = "GAMECLIENT_MODGAME";
	
	/// <summary>
	/// 获取特殊能力参数时超界:
	/// </summary>
	public const string GAMECLIENT_HERODATA_GETABILITYVALUE = "GAMECLIENT_HERODATA_GETABILITYVALUE";
	
	/// <summary>
	/// 正在购买中...
	/// </summary>
	public const string GAMECLIENT_MODIAP_BUY = "GAMECLIENT_MODIAP_BUY";
	
	/// <summary>
	/// 购买成功
	/// </summary>
	public const string GAMECLIENT_MODIAP_BUY_1 = "GAMECLIENT_MODIAP_BUY_1";
	
	/// <summary>
	/// 购买失败，请重新尝试
	/// </summary>
	public const string GAMECLIENT_MODIAP_BUY_2 = "GAMECLIENT_MODIAP_BUY_2";
	
	/// <summary>
	/// 不足
	/// </summary>
	public const string GAMECLIENT_MODIAP_BUY_3 = "GAMECLIENT_MODIAP_BUY_3";
	
	/// <summary>
	/// 新手教程
	/// </summary>
	public const string GAMECLIENT_MATCHINFO_GETMATCHNAME = "GAMECLIENT_MATCHINFO_GETMATCHNAME";
	
	/// <summary>
	/// 锦标赛_
	/// </summary>
	public const string GAMECLIENT_MATCHINFO_GETMATCHNAME_1 = "GAMECLIENT_MATCHINFO_GETMATCHNAME_1";
	
	/// <summary>
	/// 网络模式
	/// </summary>
	public const string GAMECLIENT_MATCHINFO_GETMATCHNAME_2 = "GAMECLIENT_MATCHINFO_GETMATCHNAME_2";
	
	/// <summary>
	/// 第{0}章{1}关
	/// </summary>
	public const string GAMECLIENT_MATCHINFO_GETMATCHNAME_3 = "GAMECLIENT_MATCHINFO_GETMATCHNAME_3";
	
	/// <summary>
	/// 挑战赛
	/// </summary>
	public const string GAMECLIENT_MATCHINFO_GETMATCHNAME_4 = "GAMECLIENT_MATCHINFO_GETMATCHNAME_4";
	
	/// <summary>
	/// 超凡赛车手
	/// </summary>
	public const string ISNETWORKCONNECTED = "ISNETWORKCONNECTED";
	
	/// <summary>
	/// 网络返回数据为空……
	/// </summary>
	public const string WEBREQUESTMANAGER = "WEBREQUESTMANAGER";
	
	/// <summary>
	/// 数据格式出错
	/// </summary>
	public const string WEBREQUESTMANAGER_1 = "WEBREQUESTMANAGER_1";
	
	/// <summary>
	/// 网络请求超时
	/// </summary>
	public const string WEBREQUESTMANAGER_2 = "WEBREQUESTMANAGER_2";
	
	/// <summary>
	/// 修改昵称
	/// </summary>
	public const string GAMECLIENT_MODNICKNAME_CHANGENICKNAME = "GAMECLIENT_MODNICKNAME_CHANGENICKNAME";
	
	/// <summary>
	/// 是否花费
	/// </summary>
	public const string GAMECLIENT_MODNICKNAME_CHANGENICKNAME_1 = "GAMECLIENT_MODNICKNAME_CHANGENICKNAME_1";
	
	/// <summary>
	/// 钻石修改昵称？
	/// </summary>
	public const string GAMECLIENT_MODNICKNAME_CHANGENICKNAME_2 = "GAMECLIENT_MODNICKNAME_CHANGENICKNAME_2";
	
	/// <summary>
	/// 钻石不足
	/// </summary>
	public const string GAMECLIENT_MODNICKNAME_CHANGENICKNAME_3 = "GAMECLIENT_MODNICKNAME_CHANGENICKNAME_3";
	
	/// <summary>
	/// 正在请求中...
	/// </summary>
	public const string GAMECLIENT_MODNICKNAME_CHANGENICKNAME_4 = "GAMECLIENT_MODNICKNAME_CHANGENICKNAME_4";
	
	/// <summary>
	/// 升级车手，能变得更强。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_12_UPGRADEHERO_STARTGUIDE = "GAMECLIENT_STORYGUIDE_12_UPGRADEHERO_STARTGUIDE";
	
	/// <summary>
	/// 点击这里升级车手。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_12_UPGRADEHERO_STARTGUIDE_1 = "GAMECLIENT_STORYGUIDE_12_UPGRADEHERO_STARTGUIDE_1";
	
	/// <summary>
	/// 车辆属性提升后比赛会更容易。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_13_UPGRADEBIKE_STARTGUIDE = "GAMECLIENT_STORYGUIDE_13_UPGRADEBIKE_STARTGUIDE";
	
	/// <summary>
	/// 点击进入改装界面。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_13_UPGRADEBIKE_STARTGUIDE_1 = "GAMECLIENT_STORYGUIDE_13_UPGRADEBIKE_STARTGUIDE_1";
	
	/// <summary>
	/// 点击此处升级最高速度。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_13_UPGRADEBIKE_STARTGUIDE_2 = "GAMECLIENT_STORYGUIDE_13_UPGRADEBIKE_STARTGUIDE_2";
	
	/// <summary>
	/// 选择闯关模式，开始新的比赛。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_14_GAMENORMAL_STARTGUIDE1 = "GAMECLIENT_STORYGUIDE_14_GAMENORMAL_STARTGUIDE1";
	
	/// <summary>
	/// 选择赛事第一个站开始游戏。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_14_GAMENORMAL_STARTGUIDE2 = "GAMECLIENT_STORYGUIDE_14_GAMENORMAL_STARTGUIDE2";
	
	/// <summary>
	/// 选择关卡进行游戏。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_14_GAMENORMAL_STARTGUIDE2_1 = "GAMECLIENT_STORYGUIDE_14_GAMENORMAL_STARTGUIDE2_1";
	
	/// <summary>
	/// 准备完毕，去迎接新的比赛。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_14_GAMENORMAL_STARTGUIDE2_2 = "GAMECLIENT_STORYGUIDE_14_GAMENORMAL_STARTGUIDE2_2";
	
	/// <summary>
	/// 不同的车手还有不同的能力，使用合适的车手能让比赛更简单哦。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_17_HEROBOARD_STARTGUIDE = "GAMECLIENT_STORYGUIDE_17_HEROBOARD_STARTGUIDE";
	
	/// <summary>
	/// 不同的车辆有不同的能力和属性，感受下更强的赛车给你的感觉。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_18_BIKEBOARD_STARTGUIDE = "GAMECLIENT_STORYGUIDE_18_BIKEBOARD_STARTGUIDE";
	
	/// <summary>
	/// 试试看更强的武器吧。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_19_WEAPONBOARD_STARTGUIDE = "GAMECLIENT_STORYGUIDE_19_WEAPONBOARD_STARTGUIDE";
	
	/// <summary>
	/// 点击这里购买。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_19_WEAPONBOARD_STARTGUIDE_1 = "GAMECLIENT_STORYGUIDE_19_WEAPONBOARD_STARTGUIDE_1";
	
	/// <summary>
	/// 快装备上试试吧。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_19_WEAPONBOARD_STARTGUIDE_2 = "GAMECLIENT_STORYGUIDE_19_WEAPONBOARD_STARTGUIDE_2";
	
	/// <summary>
	/// 欢迎来到疯狂赛车手的世界，接下来为你介绍相关基本操作。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE = "GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE";
	
	/// <summary>
	/// 前方有小弯道，按住左转弯就可以通过。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_1 = "GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_1";
	
	/// <summary>
	/// 发现急转弯，按住漂移展现你的漂移技术。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_2 = "GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_2";
	
	/// <summary>
	/// 使用氮气能提高车速，感受飞一般的感觉。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_3 = "GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_3";
	
	/// <summary>
	/// 有阻碍我们前进的对手了，靠近他并给予致命一击。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_4 = "GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_4";
	
	/// <summary>
	/// 前方还有对手，使用道具击坠并超过他。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_5 = "GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_5";
	
	/// <summary>
	/// 点击使用道具！
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_6 = "GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_6";
	
	/// <summary>
	/// 恭喜你赢得比赛。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_7 = "GAMECLIENT_STORYGUIDE_1_GAME_STARTGUIDE_7";
	
	/// <summary>
	/// 买了道具装备上，游戏中就可以用啦。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_20_PROPBOARD_STARTGUIDE = "GAMECLIENT_STORYGUIDE_20_PROPBOARD_STARTGUIDE";
	
	/// <summary>
	/// 你完成了一个任务，点击获得奖励吧。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_21_TASKBOARD_STARTGUIDE = "GAMECLIENT_STORYGUIDE_21_TASKBOARD_STARTGUIDE";
	
	/// <summary>
	/// 点击领取奖励。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_21_TASKBOARD_STARTGUIDE_1 = "GAMECLIENT_STORYGUIDE_21_TASKBOARD_STARTGUIDE_1";
	
	/// <summary>
	/// 钻石，金币或者燃油不够时可以在这里获取！
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_22_SHOPBOARD_STARTGUIDE = "GAMECLIENT_STORYGUIDE_22_SHOPBOARD_STARTGUIDE";
	
	/// <summary>
	/// 在这里可以和其他车手在线切磋车技！
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_23_ONLIENBOARD_STARTGUIDE = "GAMECLIENT_STORYGUIDE_23_ONLIENBOARD_STARTGUIDE";
	
	/// <summary>
	/// 参加限时赛季赛可以获得丰厚的奖励。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_24_CHAMPIONSHIPBOARD_STARTGUIDE = "GAMECLIENT_STORYGUIDE_24_CHAMPIONSHIPBOARD_STARTGUIDE";
	
	/// <summary>
	/// 计时赛中，每次通过检查点都会恢复一些时间。通过黄色标识区域会有额外奖励！
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_25_GAMEMODETIMING_STARTGUIDE = "GAMECLIENT_STORYGUIDE_25_GAMEMODETIMING_STARTGUIDE";
	
	/// <summary>
	/// 一定要在时间用尽前到达终点哦！
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_25_GAMEMODETIMING_STARTGUIDE_1 = "GAMECLIENT_STORYGUIDE_25_GAMEMODETIMING_STARTGUIDE_1";
	
	/// <summary>
	/// 挑战模式中有更刺激的比赛和更加丰富的奖励，不过有每天参加比赛有次数限定哦。
	/// </summary>
	public const string GAMECLIENT_STORYGUIDE_26_GAMEMODEBATTLE_STARTGUIDE = "GAMECLIENT_STORYGUIDE_26_GAMEMODEBATTLE_STARTGUIDE";
	
	/// <summary>
	/// 已完成
	/// </summary>
	public const string GAMECLIENT_GAMECRASHCHECKER = "GAMECLIENT_GAMECRASHCHECKER";
	
	/// <summary>
	/// 未完成
	/// </summary>
	public const string GAMECLIENT_GAMECRASHCHECKER_1 = "GAMECLIENT_GAMECRASHCHECKER_1";
	
	/// <summary>
	/// 测试
	/// </summary>
	public const string GAMECLIENT_CLIENTTEST_AWAKE = "GAMECLIENT_CLIENTTEST_AWAKE";
	
	/// <summary>
	/// 画质调节
	/// </summary>
	public const string GAMECLIENT_CLIENTTEST_WINFUNC = "GAMECLIENT_CLIENTTEST_WINFUNC";
	
	/// <summary>
	/// 关闭
	/// </summary>
	public const string GAMECLIENT_CLIENTTEST_WINFUNC_1 = "GAMECLIENT_CLIENTTEST_WINFUNC_1";
	
	/// <summary>
	/// 上次购买的物品已送达
	/// </summary>
	public const string GAMECLIENT_CACHED_ORDER_ARRIVE = "GAMECLIENT_CACHED_ORDER_ARRIVE";
	
	/// <summary>
	/// 查询失败，请重试
	/// </summary>
	public const string GAMECLIENT_Query_Order_Fail = "GAMECLIENT_Query_Order_Fail";
	
	/// <summary>
	/// 仅限体感设备用户领取
	/// </summary>
	public const string GAMECLIENT_COMMON_ORBBEC_TITLE = "GAMECLIENT_COMMON_ORBBEC_TITLE";
	
	/// <summary>
	/// 如果您已拥有体感设备，请将其连接到电视设备
	/// </summary>
	public const string GAMECLIENT_COMMON_ORBBEC_CONTENT = "GAMECLIENT_COMMON_ORBBEC_CONTENT";
	
	/// <summary>
	/// 确定
	/// </summary>
	public const string GAMECLIENT_COMMON_ORBBEC_CONFORM = "GAMECLIENT_COMMON_ORBBEC_CONFORM";
	
	/// <summary>
	/// 规则说明
	/// </summary>
	public const string GAMECLIENT_COMMON_GUIZE_TEXT = "GAMECLIENT_COMMON_GUIZE_TEXT";
	
	/// <summary>
	/// (首要目标)
	/// </summary>
	public const string GamePrepareBoard_Goal_TEXT = "GamePrepareBoard_Goal_TEXT";
	
	/// <summary>
	/// 玩家：
	/// </summary>
	public const string LobbyRoomListItem_Player = "LobbyRoomListItem_Player";
	
	/// <summary>
	/// 圈
	/// </summary>
	public const string LobbyRoomListItem_Loop = "LobbyRoomListItem_Loop";
	
	/// <summary>
	/// 正在加入房间.
	/// </summary>
	public const string LobbyRoomListItem_JoinRoom = "LobbyRoomListItem_JoinRoom";
	
	/// <summary>
	/// 随机
	/// </summary>
	public const string LobbyRoomListItem_MapOptions = "LobbyRoomListItem_MapOptions";
}
