// This code is auto generated by Excel VBA. Do NOT edit it manually !
// Copyright (C) 2016 Nanjing Xiaoxi Network Technology Co., Ltd. (http://www.xiaoxigame.com/)

using XPlugin.Localization;

public static partial class LString
{
	/// <summary>
	/// 加载UI_Prefab_Text
	/// </summary>
	public static void Load_UI_Prefab_Text()
	{
		LocalizedDict.Load("UI_Prefab_Text");
	}
	
	/// <summary>
	/// 下一步
	/// </summary>
	public const string FinishMovieBoard_BtnNext_Text = "FinishMovieBoard_BtnNext_Text";
	
	/// <summary>
	/// 首要
	/// </summary>
	public const string GameTaskBoard_Task1_Task1_Tag = "GameTaskBoard_Task1_Task1_Tag";
	
	/// <summary>
	/// 获得名次：
	/// </summary>
	public const string GameTaskBoard_Task1_Task1_Text = "GameTaskBoard_Task1_Task1_Text";
	
	/// <summary>
	/// 使用变身次数：
	/// </summary>
	public const string GameTaskBoard_Task3_Task3_Text__2_ = "GameTaskBoard_Task3_Task3_Text__2_";
	
	/// <summary>
	/// 任务：
	/// </summary>
	public const string GameTaskBoard_Title = "GameTaskBoard_Title";
	
	/// <summary>
	/// 计时赛中，通过时间检查点会恢复一些时间。
	/// </summary>
	public const string StoryGuideBoard_Word_Context_BG_TextFill_Text_ = "StoryGuideBoard_Word_Context_BG_TextFill_Text_";
	
	/// <summary>
	/// 加速带效果延长#1秒
	/// </summary>
	public const string BikeBoard_BikeInfo_BG_Ability_AbilityText = "BikeBoard_BikeInfo_BG_Ability_AbilityText";
	
	/// <summary>
	/// 满级能力:
	/// </summary>
	public const string BikeBoard_BikeInfo_BG_Ability_AbilityText__1_ = "BikeBoard_BikeInfo_BG_Ability_AbilityText__1_";
	
	/// <summary>
	///  参加条件：
	/// </summary>
	public const string ChallengeItem_ChallengeMatchItem_Top_Text = "ChallengeItem_ChallengeMatchItem_Top_Text";
	
	/// <summary>
	/// D级赛车
	/// </summary>
	public const string ChallengeItem_ChallengeMatchItem_Limit_Text = "ChallengeItem_ChallengeMatchItem_Limit_Text";
	
	/// <summary>
	/// 剩余次数：
	/// </summary>
	public const string ChallengeItem_ChallengeMatchItem_Time_Text = "ChallengeItem_ChallengeMatchItem_Time_Text";
	
	/// <summary>
	///   奖励：
	/// </summary>
	public const string ChallengeItem_ChallengeMatchItem_Reward_Text = "ChallengeItem_ChallengeMatchItem_Reward_Text";
	
	/// <summary>
	/// 参加挑战
	/// </summary>
	public const string ChallengeItem_ChallengeMatchItem_Button_Text = "ChallengeItem_ChallengeMatchItem_Button_Text";
	
	/// <summary>
	/// 赛事
	/// </summary>
	public const string ChampionshipBoard_Bottom_Image_Text = "ChampionshipBoard_Bottom_Image_Text";
	
	/// <summary>
	/// 赛事持续时间有限！
	/// </summary>
	public const string ChampionshipBoard_Bottom_GameObject_Text = "ChampionshipBoard_Bottom_GameObject_Text";
	
	/// <summary>
	/// 赛事结束时可以领取你的奖品！
	/// </summary>
	public const string ChampionshipBoard_Bottom_GameObject_Text_1 = "ChampionshipBoard_Bottom_GameObject_Text_1";
	
	/// <summary>
	/// 8小时10分钟
	/// </summary>
	public const string ChampionshipItem_ChampionshipMatchItem_Image_Text__1_ = "ChampionshipItem_ChampionshipMatchItem_Image_Text__1_";
	
	/// <summary>
	/// 道具淘汰赛
	/// </summary>
	public const string ChampionshipItem_ChampionshipMatchItem_Bottom_Text = "ChampionshipItem_ChampionshipMatchItem_Bottom_Text";
	
	/// <summary>
	/// 领取奖励
	/// </summary>
	public const string ChampionshipItem_CanReward_Image_Text = "ChampionshipItem_CanReward_Image_Text";
	
	/// <summary>
	/// 沙漠绿赛
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_Top_LevelBg_LevelName = "ChampionshipDetailBoard_RewardInfo_Top_LevelBg_LevelName";
	
	/// <summary>
	/// 12日51时42分19秒
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_Time_RemainTime = "ChampionshipDetailBoard_RewardInfo_Time_RemainTime";
	
	/// <summary>
	/// 比赛剩余:
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_Time_Lable = "ChampionshipDetailBoard_RewardInfo_Time_Lable";
	
	/// <summary>
	/// 比赛奖励
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_Text_TextBg_Text = "ChampionshipDetailBoard_RewardInfo_Text_TextBg_Text";
	
	/// <summary>
	/// 时$$$间
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Image__1__Text = "ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Image__1__Text";
	
	/// <summary>
	/// 在规定时间内完成比赛
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Text__1_ = "ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Text__1_";
	
	/// <summary>
	/// 夺$$$得
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Image__1__Text1 = "ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Image__1__Text1";
	
	/// <summary>
	/// 第一名
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Condition = "ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Condition";
	
	/// <summary>
	/// 在比赛中获得第一名
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Text__1_1 = "ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Text__1_1";
	
	/// <summary>
	/// 完$$$成
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Image__1__Text2 = "ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Image__1__Text2";
	
	/// <summary>
	/// 比赛
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Condition1 = "ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Condition1";
	
	/// <summary>
	/// 完成比赛
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Text__1_2 = "ChampionshipDetailBoard_RewardInfo_GameReward_ChampionshipRewardItem_Text__1_2";
	
	/// <summary>
	/// 排行榜奖励
	/// </summary>
	public const string ChampionshipDetailBoard_RewardInfo_Text__1__TextBg_Text = "ChampionshipDetailBoard_RewardInfo_Text__1__TextBg_Text";
	
	/// <summary>
	/// 进入比赛资格
	/// </summary>
	public const string ChampionshipDetailBoard_ChampionshipInfo_Desc_Text = "ChampionshipDetailBoard_ChampionshipInfo_Desc_Text";
	
	/// <summary>
	/// 角色限定：
	/// </summary>
	public const string ChampionshipDetailBoard_ChampionshipInfo_Condition_NeedHero_ = "ChampionshipDetailBoard_ChampionshipInfo_Condition_NeedHero_";
	
	/// <summary>
	/// 猪猪侠
	/// </summary>
	public const string ChampionshipDetailBoard_ChampionshipInfo_Condition_NeedHero__NeedHero = "ChampionshipDetailBoard_ChampionshipInfo_Condition_NeedHero__NeedHero";
	
	/// <summary>
	/// 车辆限定：
	/// </summary>
	public const string ChampionshipDetailBoard_ChampionshipInfo_Condition_NeedBike = "ChampionshipDetailBoard_ChampionshipInfo_Condition_NeedBike";
	
	/// <summary>
	/// 樱花号
	/// </summary>
	public const string ChampionshipDetailBoard_ChampionshipInfo_Condition_NeedBike_NeedBike = "ChampionshipDetailBoard_ChampionshipInfo_Condition_NeedBike_NeedBike";
	
	/// <summary>
	/// 狂野飙车赛
	/// </summary>
	public const string ChampionshipDetailBoard_ChampionshipInfo_Map_Image_MatchName = "ChampionshipDetailBoard_ChampionshipInfo_Map_Image_MatchName";
	
	/// <summary>
	/// 排名
	/// </summary>
	public const string ChampionshipDetailBoard_ChampionshipInfo_Rank_Text = "ChampionshipDetailBoard_ChampionshipInfo_Rank_Text";
	
	/// <summary>
	/// 排行榜
	/// </summary>
	public const string ChampionshipDetailBoard_ChampionshipInfo_Rank_BtnRank_Text = "ChampionshipDetailBoard_ChampionshipInfo_Rank_BtnRank_Text";
	
	/// <summary>
	/// 名$$$次
	/// </summary>
	public const string ChampionshipDetailItem_Image__1__Text = "ChampionshipDetailItem_Image__1__Text";
	
	/// <summary>
	/// 前3
	/// </summary>
	public const string ChampionshipDetailItem_Condition = "ChampionshipDetailItem_Condition";
	
	/// <summary>
	/// 在世界排行中获得前3名
	/// </summary>
	public const string ChampionshipDetailItem_Text__1_ = "ChampionshipDetailItem_Text__1_";
	
	/// <summary>
	/// 第一站
	/// </summary>
	public const string ChapterItem_Content_Image_BG_stationText = "ChapterItem_Content_Image_BG_stationText";
	
	/// <summary>
	/// 中国站
	/// </summary>
	public const string ChapterItem_Content_Image_BG_StationName_Text = "ChapterItem_Content_Image_BG_StationName_Text";
	
	/// <summary>
	/// 后解锁$$$
	/// </summary>
	public const string ChapterItem_Content_Lock_Star__1__StarCount__1_ = "ChapterItem_Content_Lock_Star__1__StarCount__1_";
	
	/// <summary>
	/// 正在加载客户端数据...
	/// </summary>
	public const string LoadingBoard_LoadingBar_Text = "LoadingBoard_LoadingBar_Text";
	
	/// <summary>
	/// 成功
	/// </summary>
	public const string GameOverBoard_Title_Text = "GameOverBoard_Title_Text";
	
	/// <summary>
	/// 人物升级
	/// </summary>
	public const string GameOverBoard_Loss_BtnHero_Text = "GameOverBoard_Loss_BtnHero_Text";
	
	/// <summary>
	/// 赛车升级
	/// </summary>
	public const string GameOverBoard_Loss_BtnBike_Text = "GameOverBoard_Loss_BtnBike_Text";
	
	/// <summary>
	/// 完成时间：
	/// </summary>
	public const string GameOverBoard_Championship_TimeLable = "GameOverBoard_Championship_TimeLable";
	
	/// <summary>
	/// 最好成绩：
	/// </summary>
	public const string GameOverBoard_Championship_TimeLable__1_ = "GameOverBoard_Championship_TimeLable__1_";
	
	/// <summary>
	/// 返回
	/// </summary>
	public const string GameOverBoard_Championship_Win_BtnBack_Text = "GameOverBoard_Championship_Win_BtnBack_Text";
	
	/// <summary>
	/// 再次挑战
	/// </summary>
	public const string GameOverBoard_Championship_Win_BtnAgain_Text = "GameOverBoard_Championship_Win_BtnAgain_Text";
	
	/// <summary>
	/// 获得奖励：
	/// </summary>
	public const string GameOverBoard_Changlling_Reward__1__Text__2_ = "GameOverBoard_Changlling_Reward__1__Text__2_";
	
	/// <summary>
	/// 使用车辆：
	/// </summary>
	public const string GameOverBoard_Changlling_Task1_RankText = "GameOverBoard_Changlling_Task1_RankText";
	
	/// <summary>
	/// 哈雷摩托
	/// </summary>
	public const string GameOverBoard_Changlling_Task1_RankText_RankText__1_ = "GameOverBoard_Changlling_Task1_RankText_RankText__1_";
	
	/// <summary>
	/// 使用武器：
	/// </summary>
	public const string GameOverBoard_Changlling_Task1__1__TotalTime = "GameOverBoard_Changlling_Task1__1__TotalTime";
	
	/// <summary>
	/// 脚
	/// </summary>
	public const string GameOverBoard_Changlling_Task1__1__TotalTime_Time = "GameOverBoard_Changlling_Task1__1__TotalTime_Time";
	
	/// <summary>
	/// 杀敌数：
	/// </summary>
	public const string GameOverBoard_Changlling_Task1__2__RankText = "GameOverBoard_Changlling_Task1__2__RankText";
	
	/// <summary>
	/// 第1名
	/// </summary>
	public const string GameOverBoard_Online_Task1_RankText_RankText__1_ = "GameOverBoard_Online_Task1_RankText_RankText__1_";
	
	/// <summary>
	/// 漂移
	/// </summary>
	public const string GamePlayBoard_BtnPlayMode_RightDrift_Text = "GamePlayBoard_BtnPlayMode_RightDrift_Text";
	
	/// <summary>
	/// 漂移距离:
	/// </summary>
	public const string GameTip_DriftTip_Text = "GameTip_DriftTip_Text";
	
	/// <summary>
	/// 氮气加速:
	/// </summary>
	public const string GameTip_BoostTip_Text = "GameTip_BoostTip_Text";
	
	/// <summary>
	/// [完成]
	/// </summary>
	public const string GameTip_TaskTip_Text = "GameTip_TaskTip_Text";
	
	/// <summary>
	/// 击杀100个敌人
	/// </summary>
	public const string GameTip_TaskTip_TextTaskInfo = "GameTip_TaskTip_TextTaskInfo";
	
	/// <summary>
	/// <size=80>被 </size><color=yellow>导弹</color> <size=80>锁定了！</size>
	/// </summary>
	public const string GameTip_LockedTip_TextLock = "GameTip_LockedTip_TextLock";
	
	/// <summary>
	/// 自动使用 <Color=yellow>护盾</color> 进行防御
	/// </summary>
	public const string GameTip_LockedTip_TextUseProp = "GameTip_LockedTip_TextUseProp";
	
	/// <summary>
	///  第      名
	/// </summary>
	public const string GameTip_GameOverTip_Text = "GameTip_GameOverTip_Text";
	
	/// <summary>
	/// 时间：
	/// </summary>
	public const string GameTip_RecoverTimeTip_Text = "GameTip_RecoverTimeTip_Text";
	
	/// <summary>
	/// 完美通过
	/// </summary>
	public const string GameTip_RecoverTimeTip_Text_Perfect = "GameTip_RecoverTimeTip_Text_Perfect";
	
	/// <summary>
	/// 第 9 名被淘汰
	/// </summary>
	public const string RaceInfo_Elimination_GameTip = "RaceInfo_Elimination_GameTip";
	
	/// <summary>
	/// 击杀数
	/// </summary>
	public const string RaceInfo_KilleTiming_Turn_Name = "RaceInfo_KilleTiming_Turn_Name";
	
	/// <summary>
	/// 圈
	/// </summary>
	public const string RaceInfo_Racing_Loop_Unit = "RaceInfo_Racing_Loop_Unit";
	
	/// <summary>
	/// 检查点
	/// </summary>
	public const string RaceInfo_Timing_Turn_Name = "RaceInfo_Timing_Turn_Name";
	
	/// <summary>
	/// 距离目标
	/// </summary>
	public const string RaceInfo_Timing_Loop_Name = "RaceInfo_Timing_Loop_Name";
	
	/// <summary>
	/// 城市漂移赛
	/// </summary>
	public const string GamePrepareBoard_Content_LevelName = "GamePrepareBoard_Content_LevelName";
	
	/// <summary>
	/// 游戏目标:
	/// </summary>
	public const string GamePrepareBoard_Content_Bottom_Image_Target = "GamePrepareBoard_Content_Bottom_Image_Target";
	
	/// <summary>
	/// 单次氮气
	/// </summary>
	public const string GamePrepareBoard_Content_Bottom_TargetInfo_Item_Des0 = "GamePrepareBoard_Content_Bottom_TargetInfo_Item_Des0";
	
	/// <summary>
	/// 取得第一名获得胜利并领取奖励
	/// </summary>
	public const string GamePrepareBoard_Content__1__Bottom_Text = "GamePrepareBoard_Content__1__Bottom_Text";
	
	/// <summary>
	/// 关卡模式
	/// </summary>
	public const string GamePrepareBoard_Bottom_Image_Top_ModeName = "GamePrepareBoard_Bottom_Image_Top_ModeName";
	
	/// <summary>
	/// 圈数:
	/// </summary>
	public const string GamePrepareBoard_Bottom_Image_Desc_Turn = "GamePrepareBoard_Bottom_Image_Desc_Turn";
	
	/// <summary>
	/// 车手:
	/// </summary>
	public const string GamePrepareBoard_Bottom_Image_Desc_Enemy = "GamePrepareBoard_Bottom_Image_Desc_Enemy";
	
	/// <summary>
	/// 时间:
	/// </summary>
	public const string GamePrepareBoard_Bottom_Image_Desc_Time = "GamePrepareBoard_Bottom_Image_Desc_Time";
	
	/// <summary>
	/// 开始游戏
	/// </summary>
	public const string GamePrepareBoard_Bottom_Start_StartLabel = "GamePrepareBoard_Bottom_Start_StartLabel";
	
	/// <summary>
	/// 哈雷火龙
	/// </summary>
	public const string GarageBoard_MotorInfo_MotorName = "GarageBoard_MotorInfo_MotorName";
	
	/// <summary>
	/// 评分：
	/// </summary>
	public const string GarageBoard_MotorInfo_ScoreName = "GarageBoard_MotorInfo_ScoreName";
	
	/// <summary>
	/// 改 装
	/// </summary>
	public const string GarageBoard_Right_Image_Update_Text = "GarageBoard_Right_Image_Update_Text";
	
	/// <summary>
	/// 选 择
	/// </summary>
	public const string GarageBoard_Right_Image_Select_Text = "GarageBoard_Right_Image_Select_Text";
	
	/// <summary>
	/// 购买
	/// </summary>
	public const string GarageBoard_Right_Image_Buy_Text = "GarageBoard_Right_Image_Buy_Text";
	
	/// <summary>
	/// 速度 :
	/// </summary>
	public const string GarageBoard_Right_Image_Bottom_Image_Speed_Name = "GarageBoard_Right_Image_Bottom_Image_Speed_Name";
	
	/// <summary>
	/// 氮气 :
	/// </summary>
	public const string GarageBoard_Right_Image_Bottom_Image_N2o_Name = "GarageBoard_Right_Image_Bottom_Image_N2o_Name";
	
	/// <summary>
	/// 加速 :
	/// </summary>
	public const string GarageBoard_Right_Image_Bottom_Image__1__Acc_Name = "GarageBoard_Right_Image_Bottom_Image__1__Acc_Name";
	
	/// <summary>
	/// 操控 :
	/// </summary>
	public const string GarageBoard_Right_Image_Bottom_Image__1__Ctl_Name = "GarageBoard_Right_Image_Bottom_Image__1__Ctl_Name";
	
	/// <summary>
	/// 阿萨德
	/// </summary>
	public const string HeroBoard_Hero_Right_Title = "HeroBoard_Hero_Right_Title";
	
	/// <summary>
	/// 操控
	/// </summary>
	public const string HeroBoard_Hero_Right_Control_Name = "HeroBoard_Hero_Right_Control_Name";
	
	/// <summary>
	/// 氮气回复比
	/// </summary>
	public const string HeroBoard_Hero_Right_N2oAdd_Name = "HeroBoard_Hero_Right_N2oAdd_Name";
	
	/// <summary>
	/// 特殊能力:
	/// </summary>
	public const string HeroBoard_Hero_Right_SpecialPower_Title_Text = "HeroBoard_Hero_Right_SpecialPower_Title_Text";
	
	/// <summary>
	/// 抵挡20%近战攻击
	/// </summary>
	public const string HeroBoard_Hero_Right_SpecialPower_Desc = "HeroBoard_Hero_Right_SpecialPower_Desc";
	
	/// <summary>
	/// 简介:
	/// </summary>
	public const string HeroBoard_Hero_Right_HeroDes_Title_Text = "HeroBoard_Hero_Right_HeroDes_Title_Text";
	
	/// <summary>
	/// 这里是角色的描述信息角色描述信息
	/// </summary>
	public const string HeroBoard_Hero_Right_HeroDes_Desc = "HeroBoard_Hero_Right_HeroDes_Desc";
	
	/// <summary>
	/// 升级
	/// </summary>
	public const string HeroBoard_Hero_Right_Update_Text = "HeroBoard_Hero_Right_Update_Text";
	
	/// <summary>
	/// 已满级
	/// </summary>
	public const string HeroBoard_Hero_Right_Update_Max = "HeroBoard_Hero_Right_Update_Max";
	
	/// <summary>
	/// 选择
	/// </summary>
	public const string HeroBoard_Hero_Right_Select_Text = "HeroBoard_Hero_Right_Select_Text";
	
	/// <summary>
	/// 宇宙沙漠
	/// </summary>
	public const string LevelChooseBoard_Text = "LevelChooseBoard_Text";
	
	/// <summary>
	/// 228星解锁
	/// </summary>
	public const string LevelItem_Pos_Title = "LevelItem_Pos_Title";
	
	/// <summary>
	/// 解锁需
	/// </summary>
	public const string LevelPage_Content_Lock_Star__1__StarCount__1_ = "LevelPage_Content_Lock_Star__1__StarCount__1_";
	
	/// <summary>
	/// 立即解锁
	/// </summary>
	public const string LevelPage_Content_BtnUnLock_Line_Text = "LevelPage_Content_BtnUnLock_Line_Text";
	
	/// <summary>
	/// 请先解锁前一章节
	/// </summary>
	public const string LevelPage_Content_UnLockTip_Text = "LevelPage_Content_UnLockTip_Text";
	
	/// <summary>
	/// 商店
	/// </summary>
	public const string MainBoard_Bottom_Left_Shop_Text = "MainBoard_Bottom_Left_Shop_Text";
	
	/// <summary>
	/// 任务$$$
	/// </summary>
	public const string MainBoard_Bottom_Left_Task_Text = "MainBoard_Bottom_Left_Task_Text";
	
	/// <summary>
	/// 道具$$$
	/// </summary>
	public const string MainBoard_Bottom_Left_Prop_Text = "MainBoard_Bottom_Left_Prop_Text";
	
	/// <summary>
	/// 武器
	/// </summary>
	public const string MainBoard_Bottom_Left_Weapon_Text = "MainBoard_Bottom_Left_Weapon_Text";
	
	/// <summary>
	/// 车手
	/// </summary>
	public const string MainBoard_Bottom_Left_Player_Text = "MainBoard_Bottom_Left_Player_Text";
	
	/// <summary>
	/// 车库
	/// </summary>
	public const string MainBoard_Bottom_Left_Garage_Text = "MainBoard_Bottom_Left_Garage_Text";
	
	/// <summary>
	/// 最高蝙蝠战车
	/// </summary>
	public const string MainBoard_UserInfo_Name_NameLabel = "MainBoard_UserInfo_Name_NameLabel";
	
	/// <summary>
	/// 更多游戏
	/// </summary>
	public const string MainBoard_Top_MoreGame_Text = "MainBoard_Top_MoreGame_Text";
	
	/// <summary>
	/// 关于
	/// </summary>
	public const string MainBoard_Top_About_Text = "MainBoard_Top_About_Text";
	
	/// <summary>
	/// 客服
	/// </summary>
	public const string MainBoard_Top_Service_Text = "MainBoard_Top_Service_Text";
	
	/// <summary>
	/// 兑换码
	/// </summary>
	public const string MainBoard_Top_Exchange_Text = "MainBoard_Top_Exchange_Text";
	
	/// <summary>
	/// 签到
	/// </summary>
	public const string MainBoard_Top_Sign_Text = "MainBoard_Top_Sign_Text";
	
	/// <summary>
	/// 首充
	/// </summary>
	public const string MainBoard_Top_FirstSpree_Text = "MainBoard_Top_FirstSpree_Text";
	
	/// <summary>
	/// 闯关模式
	/// </summary>
	public const string ModeSelectBoard_Adventure_Image__1__Text = "ModeSelectBoard_Adventure_Image__1__Text";
	
	/// <summary>
	/// 赛季模式
	/// </summary>
	public const string ModeSelectBoard_Champion_Image__4__Text = "ModeSelectBoard_Champion_Image__4__Text";
	
	/// <summary>
	/// 联网模式
	/// </summary>
	public const string ModeSelectBoard_NetMatch_Image__4__Text = "ModeSelectBoard_NetMatch_Image__4__Text";
	
	/// <summary>
	/// 挑战模式
	/// </summary>
	public const string ModeSelectBoard_Challenge_Image__4__Text = "ModeSelectBoard_Challenge_Image__4__Text";
	
	/// <summary>
	/// 赛车涂装
	/// </summary>
	public const string MotorUpdateBoard_Right_Image_ChangeColor_Text = "MotorUpdateBoard_Right_Image_ChangeColor_Text";
	
	/// <summary>
	/// 一键升满
	/// </summary>
	public const string MotorUpdateBoard_Right_Image_UpDataMax_Text = "MotorUpdateBoard_Right_Image_UpDataMax_Text";
	
	/// <summary>
	/// 比赛说明
	/// </summary>
	public const string NetMatchBoard_Bottom_Image_Text = "NetMatchBoard_Bottom_Image_Text";
	
	/// <summary>
	/// 竞速赛：
	/// </summary>
	public const string NetMatchBoard_Bottom_GameObject_Text__1_ = "NetMatchBoard_Bottom_GameObject_Text__1_";
	
	/// <summary>
	/// 以第一名的成绩完成比赛
	/// </summary>
	public const string NetMatchBoard_Bottom_GameObject_Text__1__Text = "NetMatchBoard_Bottom_GameObject_Text__1__Text";
	
	/// <summary>
	/// 竞速道具赛：
	/// </summary>
	public const string NetMatchBoard_Bottom_GameObject_Text__2_ = "NetMatchBoard_Bottom_GameObject_Text__2_";
	
	/// <summary>
	/// 淘汰赛：
	/// </summary>
	public const string NetMatchBoard_Bottom_GameObject_Text__3_ = "NetMatchBoard_Bottom_GameObject_Text__3_";
	
	/// <summary>
	/// 保持领先直至最后一名被淘汰
	/// </summary>
	public const string NetMatchBoard_Bottom_GameObject_Text__3__Text = "NetMatchBoard_Bottom_GameObject_Text__3__Text";
	
	/// <summary>
	/// 淘汰道具赛：
	/// </summary>
	public const string NetMatchBoard_Bottom_GameObject_Text__4_ = "NetMatchBoard_Bottom_GameObject_Text__4_";
	
	/// <summary>
	/// 道具名称：
	/// </summary>
	public const string PropBoard_Prop_Right_Text = "PropBoard_Prop_Right_Text";
	
	/// <summary>
	/// 导 弹
	/// </summary>
	public const string PropBoard_Prop_Right_Title = "PropBoard_Prop_Right_Title";
	
	/// <summary>
	/// 效果:
	/// </summary>
	public const string PropBoard_Prop_Right_SpecialPower_Title_Text = "PropBoard_Prop_Right_SpecialPower_Title_Text";
	
	/// <summary>
	/// 拥有 <color=#00CD00>25</color> 件
	/// </summary>
	public const string PropBoard_Prop_Right_SpecialPower_Desc = "PropBoard_Prop_Right_SpecialPower_Desc";
	
	/// <summary>
	/// 拥有数量:
	/// </summary>
	public const string PropBoard_Prop_Right_SpecialPower_Title_Text1 = "PropBoard_Prop_Right_SpecialPower_Title_Text1";
	
	/// <summary>
	/// 装 备$$$
	/// </summary>
	public const string PropBoard_Prop_Right_Select_Text = "PropBoard_Prop_Right_Select_Text";
	
	/// <summary>
	/// 名次
	/// </summary>
	public const string RankBoard_BG_Bottom_Top_Text = "RankBoard_BG_Bottom_Top_Text";
	
	/// <summary>
	/// 玩家
	/// </summary>
	public const string RankBoard_BG_Bottom_Top_Text__1_ = "RankBoard_BG_Bottom_Top_Text__1_";
	
	/// <summary>
	/// 最佳成绩
	/// </summary>
	public const string RankBoard_BG_Bottom_Top_Text__2_ = "RankBoard_BG_Bottom_Top_Text__2_";
	
	/// <summary>
	/// 所用车型
	/// </summary>
	public const string RankBoard_BG_Bottom_Top_Text__3_ = "RankBoard_BG_Bottom_Top_Text__3_";
	
	/// <summary>
	/// 猪猪侠哈哈哈哈
	/// </summary>
	public const string RankBoard_BG_Bottom_RankBoardListItem_BG_Name = "RankBoard_BG_Bottom_RankBoardListItem_BG_Name";
	
	/// <summary>
	/// 猪猪号
	/// </summary>
	public const string RankBoard_BG_Bottom_RankBoardListItem_BG_Bike = "RankBoard_BG_Bottom_RankBoardListItem_BG_Bike";
	
	/// <summary>
	/// 尚未参加该赛事！
	/// </summary>
	public const string RankBoard_BG_Bottom_SelfNull_BG_Name = "RankBoard_BG_Bottom_SelfNull_BG_Name";
	
	/// <summary>
	/// 竞速赛—反向赛
	/// </summary>
	public const string RankBtnListItem_Text = "RankBtnListItem_Text";
	
	/// <summary>
	/// 超值礼包
	/// </summary>
	public const string ShopBoard_BtnSpree_Text = "ShopBoard_BtnSpree_Text";
	
	/// <summary>
	/// 汽油瓶
	/// </summary>
	public const string ShopBoard_BtnStamina_Text = "ShopBoard_BtnStamina_Text";
	
	/// <summary>
	/// 钻 石
	/// </summary>
	public const string ShopBoard_BtnDiamond_Text__1_ = "ShopBoard_BtnDiamond_Text__1_";
	
	/// <summary>
	/// 金 币
	/// </summary>
	public const string ShopBoard_BtnCoin_Text = "ShopBoard_BtnCoin_Text";
	
	/// <summary>
	/// 全价
	/// </summary>
	public const string ShopListItem_BG_Top_Rebate_noSale = "ShopListItem_BG_Top_Rebate_noSale";
	
	/// <summary>
	/// 返利
	/// </summary>
	public const string ShopListItem_BG_Top_Rebate_Text__1__Text = "ShopListItem_BG_Top_Rebate_Text__1__Text";
	
	/// <summary>
	/// 热$$$销
	/// </summary>
	public const string ShopListItem_BG_Top_Hot_Text = "ShopListItem_BG_Top_Hot_Text";
	
	/// <summary>
	/// 金币
	/// </summary>
	public const string ShopListItem_BG_Top_Count_Name = "ShopListItem_BG_Top_Count_Name";
	
	/// <summary>
	/// 签 到
	/// </summary>
	public const string SignBoard_Text = "SignBoard_Text";
	
	/// <summary>
	/// 第7天及以后
	/// </summary>
	public const string SignBoard_Content_GameObject_SignItem_Image_Image__2__Day = "SignBoard_Content_GameObject_SignItem_Image_Image__2__Day";
	
	/// <summary>
	/// 获得奖励:
	/// </summary>
	public const string SignBoard_Content_GameObject_SignItem_Image_Image__3__RewardList = "SignBoard_Content_GameObject_SignItem_Image_Image__3__RewardList";
	
	/// <summary>
	/// <color=#FBD471FF>金币：</color>x229
	/// </summary>
	public const string SignBoard_Content_GameObject_SignItem_Image_Image__2__RewardList = "SignBoard_Content_GameObject_SignItem_Image_Image__2__RewardList";
	
	/// <summary>
	/// 已领取
	/// </summary>
	public const string SignBoard_Content_GameObject_SignItem_Mask_Image_Text = "SignBoard_Content_GameObject_SignItem_Mask_Image_Text";
	
	/// <summary>
	/// 成就奖励
	/// </summary>
	public const string TaskBoard_BG_Achieve_Text = "TaskBoard_BG_Achieve_Text";
	
	/// <summary>
	/// 每日任务
	/// </summary>
	public const string TaskBoard_BG_DailyTask_Text = "TaskBoard_BG_DailyTask_Text";
	
	/// <summary>
	/// 变身卷轴
	/// </summary>
	public const string TaskListItem_Name = "TaskListItem_Name";
	
	/// <summary>
	/// 完成一次比赛
	/// </summary>
	public const string TaskListItem_Desc = "TaskListItem_Desc";
	
	/// <summary>
	/// 领 取
	/// </summary>
	public const string TaskListItem_Btn_Text = "TaskListItem_Btn_Text";
	
	/// <summary>
	/// 玩家信息
	/// </summary>
	public const string UserInfoBoard_BG_Left_Top_Title = "UserInfoBoard_BG_Left_Top_Title";
	
	/// <summary>
	/// 杜克
	/// </summary>
	public const string UserInfoBoard_BG_Left_Top_NameBG_Name = "UserInfoBoard_BG_Left_Top_NameBG_Name";
	
	/// <summary>
	/// 你资料中的名字将对全世界的玩家可见，请输入你新的名字。
	/// </summary>
	public const string UserInfoBoard_BG_Left_Top_NameBG_Desc = "UserInfoBoard_BG_Left_Top_NameBG_Desc";
	
	/// <summary>
	/// 画       质 :
	/// </summary>
	public const string UserInfoBoard_BG_Left_Bottom_Quality_Text = "UserInfoBoard_BG_Left_Bottom_Quality_Text";
	
	/// <summary>
	///     高画质
	/// </summary>
	public const string UserInfoBoard_BG_Left_Bottom_Quality_Toggle_Text_High = "UserInfoBoard_BG_Left_Bottom_Quality_Toggle_Text_High";
	
	/// <summary>
	///     低画质
	/// </summary>
	public const string UserInfoBoard_BG_Left_Bottom_Quality_Toggle_Text_Low = "UserInfoBoard_BG_Left_Bottom_Quality_Toggle_Text_Low";
	
	/// <summary>
	/// 操作方式 :
	/// </summary>
	public const string UserInfoBoard_BG_Left_Bottom_Controller_Text = "UserInfoBoard_BG_Left_Bottom_Controller_Text";
	
	/// <summary>
	///     重    力
	/// </summary>
	public const string UserInfoBoard_BG_Left_Bottom_Controller_Toggle_Text_Gravity = "UserInfoBoard_BG_Left_Bottom_Controller_Toggle_Text_Gravity";
	
	/// <summary>
	///     按    键
	/// </summary>
	public const string UserInfoBoard_BG_Left_Bottom_Controller_Toggle_Text_Key = "UserInfoBoard_BG_Left_Bottom_Controller_Toggle_Text_Key";
	
	/// <summary>
	/// 音       乐 :
	/// </summary>
	public const string UserInfoBoard_BG_Left_Bottom_Music_Text__1_ = "UserInfoBoard_BG_Left_Bottom_Music_Text__1_";
	
	/// <summary>
	/// 音       效 :
	/// </summary>
	public const string UserInfoBoard_BG_Left_Bottom_Sound_Text__1_ = "UserInfoBoard_BG_Left_Bottom_Sound_Text__1_";
	
	/// <summary>
	/// 特殊能力 :
	/// </summary>
	public const string WeaponBoard_Weapon_Right_SpecialPower_Title_Text = "WeaponBoard_Weapon_Right_SpecialPower_Title_Text";
	
	/// <summary>
	/// 抵挡<color=#6B99D0FF>20%</color>近战攻击抵挡20%近战攻
	/// </summary>
	public const string WeaponBoard_Weapon_Right_SpecialPower_Desc = "WeaponBoard_Weapon_Right_SpecialPower_Desc";
	
	/// <summary>
	/// 简介 :
	/// </summary>
	public const string WeaponBoard_Weapon_Right_PropDes_Title_Text = "WeaponBoard_Weapon_Right_PropDes_Title_Text";
	
	/// <summary>
	/// 这是游戏的描述
	/// </summary>
	public const string WeaponBoard_Weapon_Right_PropDes_Desc = "WeaponBoard_Weapon_Right_PropDes_Desc";
	
	/// <summary>
	/// 默认武器
	/// </summary>
	public const string WeaponBoard_Weapon_Right_DefBtn_Text = "WeaponBoard_Weapon_Right_DefBtn_Text";
	
	/// <summary>
	/// 
	/// </summary>
	public const string AboutDialog_BG_Content = "AboutDialog_BG_Content";
	
	/// <summary>
	/// 提示
	/// </summary>
	public const string CommonDialog_BG_Text = "CommonDialog_BG_Text";
	
	/// <summary>
	/// 是否花费50金蛋修改昵称？
	/// </summary>
	public const string CommonDialog_BG_Content = "CommonDialog_BG_Content";
	
	/// <summary>
	/// 取消
	/// </summary>
	public const string CommonDialog_BG_BtnCancel_Text = "CommonDialog_BG_BtnCancel_Text";
	
	/// <summary>
	/// 确认
	/// </summary>
	public const string CommonDialog_BG_BtnConfirm_Text = "CommonDialog_BG_BtnConfirm_Text";
	
	/// <summary>
	/// 回到游戏
	/// </summary>
	public const string PauseDialog_Btns_BtnBack_Text = "PauseDialog_Btns_BtnBack_Text";
	
	/// <summary>
	/// 设 置
	/// </summary>
	public const string PauseDialog_Btns_BtnSetting_Text = "PauseDialog_Btns_BtnSetting_Text";
	
	/// <summary>
	/// 退出游戏
	/// </summary>
	public const string PauseDialog_Btns_BtnExit_Text = "PauseDialog_Btns_BtnExit_Text";
	
	/// <summary>
	/// 神秘敌人
	/// </summary>
	public const string PauseDialog_Name = "PauseDialog_Name";
	
	/// <summary>
	/// 淘汰赛
	/// </summary>
	public const string PauseDialog_Image__3__Desc = "PauseDialog_Image__3__Desc";
	
	/// <summary>
	/// 目标：
	/// </summary>
	public const string PauseDialog_Image__4__Image_Name = "PauseDialog_Image__4__Image_Name";
	
	/// <summary>
	/// 奖励：
	/// </summary>
	public const string PauseDialog_Image__4__Task__1__Reward_Text__2_ = "PauseDialog_Image__4__Task__1__Reward_Text__2_";
	
	/// <summary>
	/// 请输入兑换码
	/// </summary>
	public const string RedeemCodeDialog_BG_InputField_Placeholder = "RedeemCodeDialog_BG_InputField_Placeholder";
	
	/// <summary>
	/// 该兑换码已被使用，请重新输入！
	/// </summary>
	public const string RedeemCodeDialog_BG_Tip = "RedeemCodeDialog_BG_Tip";
	
	/// <summary>
	/// 确定
	/// </summary>
	public const string RedeemCodeDialog_BG_BtnYellow_Text = "RedeemCodeDialog_BG_BtnYellow_Text";
	
	/// <summary>
	/// 亲爱的玩家您好，如果您遇到任何问题我们将竭诚为您服务！$$$$$$客服QQ：2683527891$$$客服电话：400-6676918
	/// </summary>
	public const string ServiceDialog_BG_Content = "ServiceDialog_BG_Content";
	
	/// <summary>
	/// 道具不足
	/// </summary>
	public const string SupplyDialog_BG_Title = "SupplyDialog_BG_Title";
	
	/// <summary>
	/// 价格：
	/// </summary>
	public const string SupplyDialog_BG_Price = "SupplyDialog_BG_Price";
	
	/// <summary>
	/// 购 买
	/// </summary>
	public const string SupplyDialog_BG_BtnConfirm_Text = "SupplyDialog_BG_BtnConfirm_Text";
	
	/// <summary>
	/// 赛事排行榜
	/// </summary>
	public const string ChampionshipRankDialog_BG_Text = "ChampionshipRankDialog_BG_Text";
	
	/// <summary>
	/// 尚未参加该赛事
	/// </summary>
	public const string ChampionshipRankDialog_BG_SelfNull_BG_Lable = "ChampionshipRankDialog_BG_SelfNull_BG_Lable";
	
	/// <summary>
	/// 修改昵称
	/// </summary>
	public const string ChangeNickNameDialog_BG_Text = "ChangeNickNameDialog_BG_Text";
	
	/// <summary>
	/// 快给自己取一个霸气的名字吧！
	/// </summary>
	public const string ChangeNickNameDialog_BG_Desc = "ChangeNickNameDialog_BG_Desc";
	
	/// <summary>
	/// 昵称长度不超过7位
	/// </summary>
	public const string ChangeNickNameDialog_BG_InputField_Placeholder = "ChangeNickNameDialog_BG_InputField_Placeholder";
	
	/// <summary>
	/// 随机
	/// </summary>
	public const string ChangeNickNameDialog_BG_BtnRandom_Text = "ChangeNickNameDialog_BG_BtnRandom_Text";
	
	/// <summary>
	/// 匹配中...
	/// </summary>
	public const string NetPrepareDialog_NetMatchPrepareDialog_Image_Tip = "NetPrepareDialog_NetMatchPrepareDialog_Image_Tip";
	
	/// <summary>
	/// 玩家姓名
	/// </summary>
	public const string NetPrepareDialog_NetMatchPrepareDialog_List_NetPlayerItem_Text = "NetPrepareDialog_NetMatchPrepareDialog_List_NetPlayerItem_Text";
	
	/// <summary>
	/// 更换房间
	/// </summary>
	public const string NetPrepareDialog_NetMatchPrepareDialog_BtnChangeRoom_Text = "NetPrepareDialog_NetMatchPrepareDialog_BtnChangeRoom_Text";
	
	/// <summary>
	/// 退出匹配
	/// </summary>
	public const string NetPrepareDialog_NetMatchPrepareDialog_BtnExit_Text = "NetPrepareDialog_NetMatchPrepareDialog_BtnExit_Text";
	
	/// <summary>
	/// 确 定
	/// </summary>
	public const string RewardDialog_Btn_BtnYellow_BtnOK_Text = "RewardDialog_Btn_BtnYellow_BtnOK_Text";
	
	/// <summary>
	/// 关 闭
	/// </summary>
	public const string RewardDialog_Btn_BtnYellow_BtnCancel_Text = "RewardDialog_Btn_BtnYellow_BtnCancel_Text";
	
	/// <summary>
	/// 去看看
	/// </summary>
	public const string RewardDialog_Btn_BtnYellow_BtnSee_Text = "RewardDialog_Btn_BtnYellow_BtnSee_Text";
	
	/// <summary>
	/// 新车！
	/// </summary>
	public const string RewardDialog_Btn_BtnYellow_BtnSee_Text__1_ = "RewardDialog_Btn_BtnYellow_BtnSee_Text__1_";
	
	/// <summary>
	/// 获得金币
	/// </summary>
	public const string RewardDialogItem_RewardDialogItem_Image__1__Text = "RewardDialogItem_RewardDialogItem_Image__1__Text";
	
	/// <summary>
	/// 规则说明
	/// </summary>
	public const string ChampionshipRuleDialog_BG_Text__1_ = "ChampionshipRuleDialog_BG_Text__1_";
	
	/// <summary>
	/// 赛事持续时间有限！$$$赛事结束可获取奖品！$$$已结束的赛事保留3天！$$$新赛事不断更新中！
	/// </summary>
	public const string ChampionshipRuleDialog_BG_Text = "ChampionshipRuleDialog_BG_Text";
	
	/// <summary>
	/// 敬请期待
	/// </summary>
	public const string BuySuccessTip_CommonTip_Text = "BuySuccessTip_CommonTip_Text";
	
	/// <summary>
	/// 正在连接网络...
	/// </summary>
	public const string WaittingTip_Text = "WaittingTip_Text";
	
	/// <summary>
	/// 世界排行
	/// </summary>
	public const string RankBoard_BG_WorldRank_Text = "RankBoard_BG_WorldRank_Text";
	
	/// <summary>
	/// 当地排行
	/// </summary>
	public const string RankBoard_BG_LocalRank_Text = "RankBoard_BG_LocalRank_Text";
	
	/// <summary>
	/// 地区
	/// </summary>
	public const string RankBoard_BG_Bottom_Top_Text__4_ = "RankBoard_BG_Bottom_Top_Text__4_";
	
	/// <summary>
	/// 专属礼包
	/// </summary>
	public const string SensorSpreeDialog_BG_Text = "SensorSpreeDialog_BG_Text";
	
	/// <summary>
	/// 体感设备用户每日可领取礼包
	/// </summary>
	public const string SensorSpreeDialog_Content_Text = "SensorSpreeDialog_Content_Text";
	
	/// <summary>
	/// 立即领取
	/// </summary>
	public const string SensorSpreeDialog_Get_Text = "SensorSpreeDialog_Get_Text";
	
	/// <summary>
	/// 手机版
	/// </summary>
	public const string InvitePhone_Text = "InvitePhone_Text";
	
	/// <summary>
	/// 扫码下载手机版
	/// </summary>
	public const string InvitePhone_Dialog_Text = "InvitePhone_Dialog_Text";
	
	/// <summary>
	/// 武器名称：
	/// </summary>
	public const string WeaponBoard_Weapon_Text = "WeaponBoard_Weapon_Text";
	
	/// <summary>
	/// 已领取
	/// </summary>
	public const string SensorSpreeDialog_Received_Text = "SensorSpreeDialog_Received_Text";
	
	/// <summary>
	/// 选择匹配模式
	/// </summary>
	public const string ChooseOnlineMode_BG_Text = "ChooseOnlineMode_BG_Text";
	
	/// <summary>
	/// 随机匹配
	/// </summary>
	public const string ChooseOnlineMode_Random_Text = "ChooseOnlineMode_Random_Text";
	
	/// <summary>
	/// 房间匹配
	/// </summary>
	public const string ChooseOnlineMode_Room_Text = "ChooseOnlineMode_Room_Text";
	
	/// <summary>
	/// 房间列表
	/// </summary>
	public const string OnlineLobbyBoard_BG_Bg_RoomText = "OnlineLobbyBoard_BG_Bg_RoomText";
	
	/// <summary>
	/// 创建房间
	/// </summary>
	public const string OnlineLobbyBoard_BG_Bg_CreateText = "OnlineLobbyBoard_BG_Bg_CreateText";
	
	/// <summary>
	/// 加入房间
	/// </summary>
	public const string OnlineLobbyBoard_BG_Bg_InputText = "OnlineLobbyBoard_BG_Bg_InputText";
	
	/// <summary>
	/// 暂时没有可用房间
	/// </summary>
	public const string OnlineLobbyBoard_BG_Bg_tipsText = "OnlineLobbyBoard_BG_Bg_tipsText";
	
	/// <summary>
	/// 创建房间
	/// </summary>
	public const string OnlineCreateRoom_BG_Text = "OnlineCreateRoom_BG_Text";
	
	/// <summary>
	/// 需要密码:
	/// </summary>
	public const string OnlineCreateRoom_BG_NeedPassword_Text = "OnlineCreateRoom_BG_NeedPassword_Text";
	
	/// <summary>
	/// 玩家数量:
	/// </summary>
	public const string OnlineCreateRoom_BG_PlayerCount_Text = "OnlineCreateRoom_BG_PlayerCount_Text";
	
	/// <summary>
	/// 比赛地图:
	/// </summary>
	public const string OnlineCreateRoom_BG_Map_Text = "OnlineCreateRoom_BG_Map_Text";
	
	/// <summary>
	/// 比赛圈数:
	/// </summary>
	public const string OnlineCreateRoom_BG_LapCount_Text = "OnlineCreateRoom_BG_LapCount_Text";
	
	/// <summary>
	/// 比赛模式:
	/// </summary>
	public const string OnlineCreateRoom_BG_Mode_Text = "OnlineCreateRoom_BG_Mode_Text";
	
	/// <summary>
	/// 立即创建
	/// </summary>
	public const string OnlineCreateRoom_BG_BtnConfirm_Text = "OnlineCreateRoom_BG_BtnConfirm_Text";
	
	/// <summary>
	/// 加入房间
	/// </summary>
	public const string OnLineEnterRoom_BG_Title_Text = "OnLineEnterRoom_BG_Title_Text";
	
	/// <summary>
	/// 房间号:
	/// </summary>
	public const string OnLineEnterRoom_BG_RoomIdText = "OnLineEnterRoom_BG_RoomIdText";
	
	/// <summary>
	/// 密码:
	/// </summary>
	public const string OnLineEnterRoom_BG_Password_Text = "OnLineEnterRoom_BG_Password_Text";
	
	/// <summary>
	/// 立即加入
	/// </summary>
	public const string OnLineEnterRoom_BG_BtnConfirm_Text = "OnLineEnterRoom_BG_BtnConfirm_Text";
	
	/// <summary>
	/// 请输入房间号
	/// </summary>
	public const string OnLineEnterRoom_BG_RoomId_Input_Text = "OnLineEnterRoom_BG_RoomId_Input_Text";
	
	/// <summary>
	/// 选填
	/// </summary>
	public const string OnLineEnterRoom_BG_Password_Input_Text = "OnLineEnterRoom_BG_Password_Input_Text";
	
	/// <summary>
	/// 加入
	/// </summary>
	public const string ChooseOnlineMode_BtnEnter_Text = "ChooseOnlineMode_BtnEnter_Text";
	
	/// <summary>
	/// 输入密码
	/// </summary>
	public const string JoinRoomWithPwd_BG_Text = "JoinRoomWithPwd_BG_Text";
	
	/// <summary>
	/// 请输入密码
	/// </summary>
	public const string JoinRoomWithPwd_BG_Input_Text = "JoinRoomWithPwd_BG_Input_Text";
}
