// This code is auto generated by Excel VBA. Do NOT edit it manually !
// Copyright (C) 2016 Nanjing Xiaoxi Network Technology Co., Ltd. (http://www.xiaoxigame.com/)

using XPlugin.Localization;

public static partial class LString
{
	/// <summary>
	/// 加载UI_Script_Text
	/// </summary>
	public static void Load_UI_Script_Text()
	{
		LocalizedDict.Load("UI_Script_Text");
	}
	
	/// <summary>
	/// 退出
	/// </summary>
	public const string GAMEUI_ANDROIDRETURNKEY_UPDATE = "GAMEUI_ANDROIDRETURNKEY_UPDATE";
	
	/// <summary>
	/// 确认退出游戏?
	/// </summary>
	public const string GAMEUI_ANDROIDRETURNKEY_UPDATE_1 = "GAMEUI_ANDROIDRETURNKEY_UPDATE_1";
	
	/// <summary>
	/// 确定
	/// </summary>
	public const string GAMEUI_ANDROIDRETURNKEY_UPDATE_2 = "GAMEUI_ANDROIDRETURNKEY_UPDATE_2";
	
	/// <summary>
	/// 取消
	/// </summary>
	public const string GAMEUI_ANDROIDRETURNKEY_UPDATE_3 = "GAMEUI_ANDROIDRETURNKEY_UPDATE_3";
	
	/// <summary>
	/// 快速开始
	/// </summary>
	public const string GAMEUI_UIDATADE = "GAMEUI_UIDATADE";
	
	/// <summary>
	/// 加载中...
	/// </summary>
	public const string GAMEUI_GAMEUIINTERFACE_LOADSCENE = "GAMEUI_GAMEUIINTERFACE_LOADSCENE";
	
	/// <summary>
	/// 已 选 择
	/// </summary>
	public const string BIKEBOARD_SETBIKEINFO = "BIKEBOARD_SETBIKEINFO";
	
	/// <summary>
	/// 选 择
	/// </summary>
	public const string BIKEBOARD_SETBIKEINFO_1 = "BIKEBOARD_SETBIKEINFO_1";
	
	/// <summary>
	/// 购买成功！
	/// </summary>
	public const string BIKEBOARD_BUY = "BIKEBOARD_BUY";
	
	/// <summary>
	/// 不足
	/// </summary>
	public const string BIKEBOARD_BUY_1 = "BIKEBOARD_BUY_1";
	
	/// <summary>
	/// 级赛车
	/// </summary>
	public const string GAMEUI_CHALLENGEITEM_SETDATA = "GAMEUI_CHALLENGEITEM_SETDATA";
	
	/// <summary>
	/// 当前赛车等级不符
	/// </summary>
	public const string GAMEUI_CHALLENGEITEM_ONCLICK = "GAMEUI_CHALLENGEITEM_ONCLICK";
	
	/// <summary>
	/// 已关闭
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPITEM_REFRESHTIME = "GAMEUI_CHAMPIONSHIPITEM_REFRESHTIME";
	
	/// <summary>
	/// 奖励已领取！
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPITEM_ONCLICK = "GAMEUI_CHAMPIONSHIPITEM_ONCLICK";
	
	/// <summary>
	/// 未获得奖励
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPITEM_ONCLICK_1 = "GAMEUI_CHAMPIONSHIPITEM_ONCLICK_1";
	
	/// <summary>
	/// 无
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPDETAILBOARD_INIT = "GAMEUI_CHAMPIONSHIPDETAILBOARD_INIT";
	
	/// <summary>
	/// 级车
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPDETAILBOARD_INIT_1 = "GAMEUI_CHAMPIONSHIPDETAILBOARD_INIT_1";
	
	/// <summary>
	/// 已结束
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPDETAILBOARD_REFRESHTIME = "GAMEUI_CHAMPIONSHIPDETAILBOARD_REFRESHTIME";
	
	/// <summary>
	/// 正在请求排行榜...
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPDETAILBOARD_ONBTNRANKCLICK = "GAMEUI_CHAMPIONSHIPDETAILBOARD_ONBTNRANKCLICK";
	
	/// <summary>
	/// 排行榜获取失败
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPDETAILBOARD_ONBTNRANKCLICK_1 = "GAMEUI_CHAMPIONSHIPDETAILBOARD_ONBTNRANKCLICK_1";
	
	/// <summary>
	/// 本赛事限定角色：$$$<color=#21FF78FF>
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPDETAILBOARD_ONENTERPREPARE = "GAMEUI_CHAMPIONSHIPDETAILBOARD_ONENTERPREPARE";
	
	/// <summary>
	/// 本赛事限定赛车等级：$$$<color=#21FF78FF>
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPDETAILBOARD_ONENTERPREPARE_1 = "GAMEUI_CHAMPIONSHIPDETAILBOARD_ONENTERPREPARE_1";
	
	/// <summary>
	/// 本赛事限定赛车：\n<color=#21FF78FF>
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPDETAILBOARD_ONENTERPREPARE_2 = "GAMEUI_CHAMPIONSHIPDETAILBOARD_ONENTERPREPARE_2";
	
	/// <summary>
	/// 能量不够
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPDETAILBOARD_ONENTERPREPARE_3 = "GAMEUI_CHAMPIONSHIPDETAILBOARD_ONENTERPREPARE_3";
	
	/// <summary>
	/// 前
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPRANKREWARDITEM = "GAMEUI_CHAMPIONSHIPRANKREWARDITEM";
	
	/// <summary>
	/// 在世界排行中获得前
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPRANKREWARDITEM_1 = "GAMEUI_CHAMPIONSHIPRANKREWARDITEM_1";
	
	/// <summary>
	/// 名
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPRANKREWARDITEM_2 = "GAMEUI_CHAMPIONSHIPRANKREWARDITEM_2";
	
	/// <summary>
	/// 在规定时间内完成比赛
	/// </summary>
	public const string GAMEUI_CHAMPIONSHIPRANKREWARDITEM_3 = "GAMEUI_CHAMPIONSHIPRANKREWARDITEM_3";
	
	/// <summary>
	/// 解锁关卡
	/// </summary>
	public const string GAMEUI_CHAPTERCHOOSEBOARD_CELLVIEWSELECTED = "GAMEUI_CHAPTERCHOOSEBOARD_CELLVIEWSELECTED";
	
	/// <summary>
	/// 是否使用
	/// </summary>
	public const string GAMEUI_CHAPTERCHOOSEBOARD_CELLVIEWSELECTED_1 = "GAMEUI_CHAPTERCHOOSEBOARD_CELLVIEWSELECTED_1";
	
	/// <summary>
	/// 确认
	/// </summary>
	public const string GAMEUI_CHAPTERCHOOSEBOARD_CELLVIEWSELECTED_2 = "GAMEUI_CHAPTERCHOOSEBOARD_CELLVIEWSELECTED_2";
	
	/// <summary>
	/// 解锁成功
	/// </summary>
	public const string GAMEUI_CHAPTERCHOOSEBOARD_CELLVIEWSELECTED_3 = "GAMEUI_CHAPTERCHOOSEBOARD_CELLVIEWSELECTED_3";
	
	/// <summary>
	/// 请先解锁上一章
	/// </summary>
	public const string GAMEUI_CHAPTERCHOOSEBOARD_CELLVIEWSELECTED_4 = "GAMEUI_CHAPTERCHOOSEBOARD_CELLVIEWSELECTED_4";
	
	/// <summary>
	/// 完成
	/// </summary>
	public const string GAMEUI_GAMEOVERBOARD_WIN = "GAMEUI_GAMEOVERBOARD_WIN";
	
	/// <summary>
	/// 成功
	/// </summary>
	public const string GAMEUI_GAMEOVERBOARD_WIN_1 = "GAMEUI_GAMEOVERBOARD_WIN_1";
	
	/// <summary>
	/// 失败
	/// </summary>
	public const string GAMEUI_GAMEOVERBOARD_LOSS = "GAMEUI_GAMEOVERBOARD_LOSS";
	
	/// <summary>
	/// 第{0}天
	/// </summary>
	public const string GAMEUI_UIGAMEOVERINFOONLINE_INIT = "GAMEUI_UIGAMEOVERINFOONLINE_INIT";
	
	/// <summary>
	/// 第7天及以后
	/// </summary>
	public const string GAMEUI_UIGAMEOVERINFOONLINE_INIT_2 = "GAMEUI_UIGAMEOVERINFOONLINE_INIT_2";
	
	/// <summary>
	/// 天
	/// </summary>
	public const string COMMONUTIL_GETFORMATTIMEDHMS = "COMMONUTIL_GETFORMATTIMEDHMS";
	
	/// <summary>
	/// 时
	/// </summary>
	public const string COMMONUTIL_GETFORMATTIMEDHMS_1 = "COMMONUTIL_GETFORMATTIMEDHMS_1";
	
	/// <summary>
	/// 分
	/// </summary>
	public const string COMMONUTIL_GETFORMATTIMEDHMS_2 = "COMMONUTIL_GETFORMATTIMEDHMS_2";
	
	/// <summary>
	/// 秒
	/// </summary>
	public const string COMMONUTIL_GETFORMATTIMEDHMS_3 = "COMMONUTIL_GETFORMATTIMEDHMS_3";
	
	/// <summary>
	/// <size=80>被 </size><color=yellow>
	/// </summary>
	public const string GAMEUI_GAMETIP_RESET = "GAMEUI_GAMETIP_RESET";
	
	/// <summary>
	/// </color> <size=80>锁定了！</size>
	/// </summary>
	public const string GAMEUI_GAMETIP_RESET_1 = "GAMEUI_GAMETIP_RESET_1";
	
	/// <summary>
	/// 时间剩余: 
	/// </summary>
	public const string GAMEUI_GAMETIP_ONGAMEOVER = "GAMEUI_GAMETIP_ONGAMEOVER";
	
	/// <summary>
	///  秒
	/// </summary>
	public const string GAMEUI_GAMETIP_ONGAMEOVER_1 = "GAMEUI_GAMETIP_ONGAMEOVER_1";
	
	/// <summary>
	/// 时间结束！
	/// </summary>
	public const string GAMEUI_GAMETIP_ONGAMEOVER_2 = "GAMEUI_GAMETIP_ONGAMEOVER_2";
	
	/// <summary>
	/// 击杀了 
	/// </summary>
	public const string GAMEUI_GAMETIP_ONGAMEOVER_3 = "GAMEUI_GAMETIP_ONGAMEOVER_3";
	
	/// <summary>
	///  人
	/// </summary>
	public const string GAMEUI_GAMETIP_ONGAMEOVER_4 = "GAMEUI_GAMETIP_ONGAMEOVER_4";
	
	/// <summary>
	///  第      名
	/// </summary>
	public const string GAMEUI_GAMETIP_ONGAMEOVER_5 = "GAMEUI_GAMETIP_ONGAMEOVER_5";
	
	/// <summary>
	/// 你已被淘汰
	/// </summary>
	public const string GAMEUI_UIRACEINFOELIMINATION_SHOWELIMINATETIP = "GAMEUI_UIRACEINFOELIMINATION_SHOWELIMINATETIP";
	
	/// <summary>
	/// 第 
	/// </summary>
	public const string GAMEUI_UIRACEINFOELIMINATION_SHOWELIMINATETIP_1 = "GAMEUI_UIRACEINFOELIMINATION_SHOWELIMINATETIP_1";
	
	/// <summary>
	///  名被淘汰
	/// </summary>
	public const string GAMEUI_UIRACEINFOELIMINATION_SHOWELIMINATETIP_2 = "GAMEUI_UIRACEINFOELIMINATION_SHOWELIMINATETIP_2";
	
	/// <summary>
	/// 获得第一名并领取奖励
	/// </summary>
	public const string GAMEUI_GAMEPREPAREBOARD_INIT = "GAMEUI_GAMEPREPAREBOARD_INIT";
	
	/// <summary>
	/// 本关卡限定角色：$$$<color=#21FF78FF>
	/// </summary>
	public const string GAMEUI_GAMEPREPAREBOARD_UPDATEMOTORINFO = "GAMEUI_GAMEPREPAREBOARD_UPDATEMOTORINFO";
	
	/// <summary>
	/// 本关卡限定赛车：$$$<color=#21FF78FF>
	/// </summary>
	public const string GAMEUI_GAMEPREPAREBOARD_UPDATEMOTORINFO_1 = "GAMEUI_GAMEPREPAREBOARD_UPDATEMOTORINFO_1";
	
	/// <summary>
	/// 提示
	/// </summary>
	public const string GAMEUI_BTNFIRSTSPREE_ONPOINTERCLICK = "GAMEUI_BTNFIRSTSPREE_ONPOINTERCLICK";
	
	/// <summary>
	/// 功能尚未开放！
	/// </summary>
	public const string GAMEUI_BTNFIRSTSPREE_ONPOINTERCLICK_1 = "GAMEUI_BTNFIRSTSPREE_ONPOINTERCLICK_1";
	
	/// <summary>
	/// 敬请期待！
	/// </summary>
	public const string GAMEUI_MAINMENUBOARD_ONBTNNETMATCHCLICK = "GAMEUI_MAINMENUBOARD_ONBTNNETMATCHCLICK";
	
	/// <summary>
	/// 收集<color=#21FF78FF>9颗星</color>后开启
	/// </summary>
	public const string GAMEUI_MAINMENUBOARD_ONBTNNETMATCHCLICK_1 = "GAMEUI_MAINMENUBOARD_ONBTNNETMATCHCLICK_1";
	
	/// <summary>
	/// 正在连接中...
	/// </summary>
	public const string GAMEUI_MAINMENUBOARD_ONBTNNETMATCHCLICK_2 = "GAMEUI_MAINMENUBOARD_ONBTNNETMATCHCLICK_2";
	
	/// <summary>
	/// 网络错误
	/// </summary>
	public const string GAMEUI_MAINMENUBOARD_ONBTNNETMATCHCLICK_3 = "GAMEUI_MAINMENUBOARD_ONBTNNETMATCHCLICK_3";
	
	/// <summary>
	/// 当前网络不可用$$$请检查设置
	/// </summary>
	public const string GAMEUI_MAINMENUBOARD_ONBTNNETMATCHCLICK_4 = "GAMEUI_MAINMENUBOARD_ONBTNNETMATCHCLICK_4";
	
	/// <summary>
	/// 正在获取赛事
	/// </summary>
	public const string GAMEUI_MAINMENUBOARD_SHOWCHAMPIONSHIPBOARD = "GAMEUI_MAINMENUBOARD_SHOWCHAMPIONSHIPBOARD";
	
	/// <summary>
	/// 一大波赛事即将来临！
	/// </summary>
	public const string GAMEUI_MAINMENUBOARD_SHOWCHAMPIONSHIPBOARD_1 = "GAMEUI_MAINMENUBOARD_SHOWCHAMPIONSHIPBOARD_1";
	
	/// <summary>
	/// 已完成
	/// </summary>
	public const string GAMEUI_GAMETASKBOARD_SETTASKS = "GAMEUI_GAMETASKBOARD_SETTASKS";
	
	/// <summary>
	/// 已选择
	/// </summary>
	public const string GAMEUI_GARAGEBOARD_SHOWBIKE = "GAMEUI_GARAGEBOARD_SHOWBIKE";
	
	/// <summary>
	/// 选择
	/// </summary>
	public const string GAMEUI_GARAGEBOARD_SHOWBIKE_1 = "GAMEUI_GARAGEBOARD_SHOWBIKE_1";
	
	/// <summary>
	/// 星解锁
	/// </summary>
	public const string GAMEUI_LEVELITEM_SETDATA = "GAMEUI_LEVELITEM_SETDATA";
	
	/// <summary>
	/// 尚未解锁该关卡
	/// </summary>
	public const string GAMEUI_LEVELITEM_ONPOINTERCLICK = "GAMEUI_LEVELITEM_ONPOINTERCLICK";
	
	/// <summary>
	/// 全部满星可领
	/// </summary>
	public const string GAMEUI_REWARDCASE_ONPOINTERCLICK = "GAMEUI_REWARDCASE_ONPOINTERCLICK";
	
	/// <summary>
	/// 奖励已领取
	/// </summary>
	public const string GAMEUI_REWARDCASE_ONPOINTERCLICK_1 = "GAMEUI_REWARDCASE_ONPOINTERCLICK_1";
	
	/// <summary>
	/// 正在请求排行榜数据...
	/// </summary>
	public const string GAMEUI_TOPFUNCLASS_ONBTNRANKCLICK = "GAMEUI_TOPFUNCLASS_ONBTNRANKCLICK";
	
	/// <summary>
	/// 暂无排行榜数据，请稍后重试
	/// </summary>
	public const string GAMEUI_TOPFUNCLASS_ONBTNRANKCLICK_1 = "GAMEUI_TOPFUNCLASS_ONBTNRANKCLICK_1";
	
	/// <summary>
	/// 网络异常，请稍后重试！
	/// </summary>
	public const string GAMEUI_TOPFUNCLASS_ONBTNRANKCLICK_2 = "GAMEUI_TOPFUNCLASS_ONBTNRANKCLICK_2";
	
	/// <summary>
	/// 正在获取赛事...
	/// </summary>
	public const string GAMEUI_TOPFUNCLASS_SHOWCHAMPIONSHIPBOARD = "GAMEUI_TOPFUNCLASS_SHOWCHAMPIONSHIPBOARD";
	
	/// <summary>
	/// 拥有 <color=#00CD00>
	/// </summary>
	public const string GAMEUI_PROPBOARD_SETDETAILINFO = "GAMEUI_PROPBOARD_SETDETAILINFO";
	
	/// <summary>
	/// </color> 件
	/// </summary>
	public const string GAMEUI_PROPBOARD_SETDETAILINFO_1 = "GAMEUI_PROPBOARD_SETDETAILINFO_1";
	
	/// <summary>
	/// 卸下
	/// </summary>
	public const string GAMEUI_PROPBOARD_SETBTNEQUIPTXT = "GAMEUI_PROPBOARD_SETBTNEQUIPTXT";
	
	/// <summary>
	/// 装备
	/// </summary>
	public const string GAMEUI_PROPBOARD_SETBTNEQUIPTXT_1 = "GAMEUI_PROPBOARD_SETBTNEQUIPTXT_1";
	
	/// <summary>
	/// 元
	/// </summary>
	public const string GAMEUI_SHOPLISTITEM_ONBTNBUYCLICK = "GAMEUI_SHOPLISTITEM_ONBTNBUYCLICK";
	
	/// <summary>
	/// 购买
	/// </summary>
	public const string GAMEUI_SHOPLISTITEM_ONBTNBUYCLICK_1 = "GAMEUI_SHOPLISTITEM_ONBTNBUYCLICK_1";
	
	/// <summary>
	/// 确认花费{0}{1}购买\n{2}吗?
	/// </summary>
	public const string GAMEUI_SHOPLISTITEM_ONBTNBUYCLICK_2 = "GAMEUI_SHOPLISTITEM_ONBTNBUYCLICK_2";
	
	/// <summary>
	/// 第7天及以后
	/// </summary>
	public const string GAMEUI_SIGNITEM_SETDATA = "GAMEUI_SIGNITEM_SETDATA";
	
	/// <summary>
	/// 正在请求服务器...
	/// </summary>
	public const string GAMEUI_SIGNITEM_ONBTNCLICK = "GAMEUI_SIGNITEM_ONBTNCLICK";
	
	/// <summary>
	/// 网络请求失败，请重试
	/// </summary>
	public const string GAMEUI_SIGNITEM_ONBTNCLICK_1 = "GAMEUI_SIGNITEM_ONBTNCLICK_1";
	
	/// <summary>
	/// 未完成
	/// </summary>
	public const string GAMEUI_BTNTASK_SETDATA = "GAMEUI_BTNTASK_SETDATA";
	
	/// <summary>
	/// 领取
	/// </summary>
	public const string GAMEUI_BTNTASK_SETDATA_1 = "GAMEUI_BTNTASK_SETDATA_1";
	
	/// <summary>
	/// 已领取
	/// </summary>
	public const string GAMEUI_BTNTASK_SETDATA_2 = "GAMEUI_BTNTASK_SETDATA_2";
	
	/// <summary>
	/// 未开启
	/// </summary>
	public const string GAMEUI_BTNTASK_SETDATA_3 = "GAMEUI_BTNTASK_SETDATA_3";
	
	/// <summary>
	/// 获得
	/// </summary>
	public const string GAMEUI_REWARDITEM_SETDATA = "GAMEUI_REWARDITEM_SETDATA";
	
	/// <summary>
	/// 领取失败
	/// </summary>
	public const string GAMEUI_TASKLISTITEM_GETREWARD = "GAMEUI_TASKLISTITEM_GETREWARD";
	
	/// <summary>
	/// 永久拥有
	/// </summary>
	public const string GAMEUI_WEAPONBOARD_SETDETAILINFO = "GAMEUI_WEAPONBOARD_SETDETAILINFO";
	
	/// <summary>
	///   <size=30>(每局游戏消耗1个)</size>
	/// </summary>
	public const string GAMEUI_WEAPONBOARD_SETDETAILINFO_1 = "GAMEUI_WEAPONBOARD_SETDETAILINFO_1";
	
	/// <summary>
	/// 初始武器不能卸下
	/// </summary>
	public const string GAMEUI_WEAPONBOARD_ONBTNEQUIPCLICK = "GAMEUI_WEAPONBOARD_ONBTNEQUIPCLICK";
	
	/// <summary>
	/// 武器数量不足
	/// </summary>
	public const string GAMEUI_WEAPONBOARD_ONBTNEQUIPCLICK_1 = "GAMEUI_WEAPONBOARD_ONBTNEQUIPCLICK_1";
	
	/// <summary>
	/// 昵称不能为空
	/// </summary>
	public const string GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK = "GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK";
	
	/// <summary>
	/// 包含敏感字
	/// </summary>
	public const string GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK_1 = "GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK_1";
	
	/// <summary>
	/// 昵称修改成功！
	/// </summary>
	public const string GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK_2 = "GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK_2";
	
	/// <summary>
	/// 昵称修改失败
	/// </summary>
	public const string GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK_3 = "GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK_3";
	
	/// <summary>
	/// 正在请求中...
	/// </summary>
	public const string GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK_4 = "GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK_4";
	
	/// <summary>
	/// 该昵称已存在
	/// </summary>
	public const string GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK_5 = "GAMEUI_CHANGENICKNAMEDIALOG_ONBTNOKCLICK_5";
	
	/// <summary>
	/// 兑换码不可为空
	/// </summary>
	public const string REDEEMCODEDIALOG_ONBTNOKCLICK = "REDEEMCODEDIALOG_ONBTNOKCLICK";
	
	/// <summary>
	/// 请稍候...
	/// </summary>
	public const string REDEEMCODEDIALOG_ONBTNOKCLICK_1 = "REDEEMCODEDIALOG_ONBTNOKCLICK_1";
	
	/// <summary>
	/// 请求失败，请重新尝试
	/// </summary>
	public const string REDEEMCODEDIALOG_ONBTNOKCLICK_2 = "REDEEMCODEDIALOG_ONBTNOKCLICK_2";
	
	/// <summary>
	/// 兑换成功
	/// </summary>
	public const string REDEEMCODEDIALOG_ONBTNOKCLICK_3 = "REDEEMCODEDIALOG_ONBTNOKCLICK_3";
	
	/// <summary>
	/// 该兑换码已被使用，请重新输入！
	/// </summary>
	public const string REDEEMCODEDIALOG_ONBTNOKCLICK_4 = "REDEEMCODEDIALOG_ONBTNOKCLICK_4";
	
	/// <summary>
	/// 兑换码错误，请重新输入！
	/// </summary>
	public const string REDEEMCODEDIALOG_ONBTNOKCLICK_5 = "REDEEMCODEDIALOG_ONBTNOKCLICK_5";
	
	/// <summary>
	/// 购买成功
	/// </summary>
	public const string GAMEUI_SUPPLYDIALOG_ONBTNOKCLICK = "GAMEUI_SUPPLYDIALOG_ONBTNOKCLICK";
	
	/// <summary>
	/// 未加入
	/// </summary>
	public const string NETPLAYERITEM_SETACTIVE = "NETPLAYERITEM_SETACTIVE";
	
	/// <summary>
	/// 匹配中.
	/// </summary>
	public const string NETPREPAREDIALOG_SHOWTIP = "NETPREPAREDIALOG_SHOWTIP";
	
	/// <summary>
	/// 匹配中..
	/// </summary>
	public const string NETPREPAREDIALOG_SHOWTIP_1 = "NETPREPAREDIALOG_SHOWTIP_1";
	
	/// <summary>
	/// 匹配中...
	/// </summary>
	public const string NETPREPAREDIALOG_SHOWTIP_2 = "NETPREPAREDIALOG_SHOWTIP_2";
	
	/// <summary>
	/// 准备开始！
	/// </summary>
	public const string NETPREPAREDIALOG_SHOWTIP_3 = "NETPREPAREDIALOG_SHOWTIP_3";
	
	/// <summary>
	/// 正在请求换房...
	/// </summary>
	public const string NETPREPAREDIALOG_ONBTNCHANGEROOMCLICK = "NETPREPAREDIALOG_ONBTNCHANGEROOMCLICK";
	
	/// <summary>
	/// 新车！
	/// </summary>
	public const string GAMEUI_REWARDDIALOG_SETSEEWHAT = "GAMEUI_REWARDDIALOG_SETSEEWHAT";
	
	/// <summary>
	/// 新角色！
	/// </summary>
	public const string GAMEUI_REWARDDIALOG_SETSEEWHAT_1 = "GAMEUI_REWARDDIALOG_SETSEEWHAT_1";
	
	/// <summary>
	/// 领 取
	/// </summary>
	public const string FIRSTSPREEDIALOG_SETBTNNAME = "FIRSTSPREEDIALOG_SETBTNNAME";
	
	/// <summary>
	/// 立即充值
	/// </summary>
	public const string FIRSTSPREEDIALOG_SETBTNNAME_1 = "FIRSTSPREEDIALOG_SETBTNNAME_1";
	
	/// <summary>
	/// 购买失败，请重新尝试
	/// </summary>
	public const string GAMEUI_RMBSPREEDIALOG_BUY = "GAMEUI_RMBSPREEDIALOG_BUY";
	
	/// <summary>
	/// 确认花费 
	/// </summary>
	public const string GAMEUI_RMBSPREEDIALOG_ONBTNOKCLICK = "GAMEUI_RMBSPREEDIALOG_ONBTNOKCLICK";
	
	/// <summary>
	/// 元 购买$$$
	/// </summary>
	public const string GAMEUI_RMBSPREEDIALOG_ONBTNOKCLICK_1 = "GAMEUI_RMBSPREEDIALOG_ONBTNOKCLICK_1";
	
	/// <summary>
	///  吗？
	/// </summary>
	public const string GAMEUI_RMBSPREEDIALOG_ONBTNOKCLICK_2 = "GAMEUI_RMBSPREEDIALOG_ONBTNOKCLICK_2";
	
	/// <summary>
	/// 新手宝箱
	/// </summary>
	public const string GAMEUI_SPREEDIALOG_SETTITLE = "GAMEUI_SPREEDIALOG_SETTITLE";
	
	/// <summary>
	/// 获得 
	/// </summary>
	public const string GAMEUI_TIPITEM_SHOW = "GAMEUI_TIPITEM_SHOW";
	
	/// <summary>
	/// 第{0}名
	/// </summary>
	public const string GAMEUI_RANK = "GAMEUI_RANK";
	
	/// <summary>
	/// 仅MTN游戏会员能参加
	/// </summary>
	public const string ONLY_MTN_MEMBER = "ONLY_MTN_MEMBER";
}
